### ISSUE TITLE
tpknam in memo

### ISSUE THREAD

**Issue by encipher88** [heliaxdev/hermes#21]
SE: how i can include my public key (tpknam) as the –memo for all transactions in hermes memo_prefix = '' ?
Specify a string that Hermes will use as a memo for each transaction it submits to this chain. 
The string is limited to 50 characters. 
but tpknam is 66 characters.

**Comment by yito88** [comment]
We have another branch that allows you to have a memo of up to 200 characters.
https://github.com/heliaxdev/hermes/tree/1.7.4-namada-long-memo
